-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 16:00:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`TblUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblUsuario` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `NomeUser` VARCHAR(45) ,
  `CPFUser` VARCHAR(20) ,
  `EmailUser` VARCHAR(45) ,
  `TelUser` VARCHAR(45) ,
  `DataNascUser` DATE ,
  `GeneroUser` VARCHAR(1) ,
  `SenhaUser` VARCHAR(20) ,
  `ImgUser` VARCHAR(200) ,
  `DescUser` VARCHAR(200) ,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblCargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblCargo` (
  `SiglaCargo` VARCHAR(10) NOT NULL,
  `NomeCargo` VARCHAR(45) NULL,
  PRIMARY KEY (`SiglaCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblSaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblSaldo` (
  `idUser` INT NOT NULL,
  `QuantSaldo` DOUBLE NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_TblSaldo_TblUsuario_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_TblSaldo_TblUsuario`
    FOREIGN KEY (`idUser`)
    REFERENCES `sistema`.`TblUsuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblTipoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblTipoServico` (
  `NomeServ` VARCHAR(45) NOT NULL,
  `CategoriaServ` VARCHAR(45) NULL,
  PRIMARY KEY (`NomeServ`))
ENGINE = InnoDB;

ALTER TABLE TblTipoServico auto_increment = 1;

-- -----------------------------------------------------
-- Table `sistema`.`TblAnunUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblAnunUser` (
  `idAnunUser` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `NomeServ` VARCHAR(45) NOT NULL,
  `TituloAnunUser` VARCHAR(20) NOT NULL,
  `DescAnunUser` VARCHAR(255) NOT NULL,
  `PrecoAnunUser` DOUBLE NOT NULL,
  `RequisitosAnunUser` VARCHAR(45) NOT NULL,
  `ImgAnunUser` VARCHAR(200),
  `StatusAnunUser` TINYINT(1),
  `DataAnunUser` DATE,
  PRIMARY KEY (`idAnunUser`),
  INDEX `fk_TblAnunUser_TblUsuario1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_TblAnunUser_TblTipoServico1_idx` (`NomeServ` ASC) VISIBLE,
  CONSTRAINT `fk_TblAnunUser_TblUsuario1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sistema`.`TblUsuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TblAnunUser_TblTipoServico1`
    FOREIGN KEY (`NomeServ`)
    REFERENCES `sistema`.`TblTipoServico` (`NomeServ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblFuncionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblFuncionario` (
  `idFunc` INT NOT NULL AUTO_INCREMENT,
  `SiglaCargo` VARCHAR(10) NOT NULL,
  `NomeFunc` VARCHAR(45) NOT NULL,
  `CPFFunc` VARCHAR(20) NOT NULL,
  `EmailFunc` VARCHAR(45) NOT NULL,
  `TelFunc` VARCHAR(20) NOT NULL,
  `DataNascFunc` DATE NOT NULL,
  `GeneroFunc` VARCHAR(1) NOT NULL,
  `SenhaFunc` VARCHAR(45) NOT NULL,
  `ImgFunc` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idFunc`),
  INDEX `fk_TblFuncionario_TblCargo1_idx` (`SiglaCargo` ASC) VISIBLE,
  CONSTRAINT `fk_TblFuncionario_TblCargo1`
    FOREIGN KEY (`SiglaCargo`)
    REFERENCES `sistema`.`TblCargo` (`SiglaCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblTicket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idFunc` INT NOT NULL,
  `StatusTicket` TINYINT(1) NOT NULL,
  `BoletimOcorrencia` VARCHAR(255) NOT NULL,
  `TipoTicket` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_TblTicket_TblUsuario1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_TblTicket_TblFuncionario1_idx` (`idFunc` ASC) VISIBLE,
  CONSTRAINT `fk_TblTicket_TblUsuario1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sistema`.`TblUsuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TblTicket_TblFuncionario1`
    FOREIGN KEY (`idFunc`)
    REFERENCES `sistema`.`TblFuncionario` (`idFunc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblChatTicket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblChatTicket` (
  `idChatTicket` INT NOT NULL AUTO_INCREMENT,
  `idTicket` INT NOT NULL,
  `ChatTicketMensagemTexto` VARCHAR(255) NULL,
  `ChatTicketMensagemDataHora` DATETIME NULL,
  `ChatTicketMensagemImagem` VARCHAR(100) NULL,
  PRIMARY KEY (`idChatTicket`),
  INDEX `fk_TblChatTicket_TblTicket1_idx` (`idTicket` ASC) VISIBLE,
  CONSTRAINT `fk_TblChatTicket_TblTicket1`
    FOREIGN KEY (`idTicket`)
    REFERENCES `sistema`.`TblTicket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblFreelancer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblFreelancer` (
  `idFr` INT NOT NULL AUTO_INCREMENT,
  `CompetenciasFr` VARCHAR(255) NULL,
  `EspecialidadesFr` VARCHAR(255) NULL,
  `NomeFr` VARCHAR(70) NULL,
  `CPFFr` VARCHAR(20) NULL,
  `EmailFr` VARCHAR(45) NULL,
  `TelFr` VARCHAR(20) NULL,
  `DataNascFr` DATE NULL,
  `GeneroFr` VARCHAR(1) NULL,
  `SenharFr` VARCHAR(45) NULL,
  `ImgFr` VARCHAR(100) NULL,
  `DescFr` VARCHAR(200) ,
  PRIMARY KEY (`idFr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblOfertaF_U`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblOfertaF_U` (
  `idOfertaFU` INT NOT NULL AUTO_INCREMENT,
  `idFr` INT NOT NULL,
  `idAnunUser` INT NOT NULL,
  `PropostaOfertaFU` VARCHAR(255) NOT NULL,
  `PrecoOfertaFU` DOUBLE NOT NULL,
  `ImagemOfertaFU` VARCHAR(100) NULL,
  `DataOfertaFU` DATE NOT NULL,
  `StatusOfertaFU` TINYINT(1) NULL,
  PRIMARY KEY (`idOfertaFU`),
  INDEX `fk_TblOfertaF_U_TblFreelancer1_idx` (`idFr` ASC) VISIBLE,
  INDEX `fk_TblOfertaF_U_TblAnunUser1_idx` (`idAnunUser` ASC) VISIBLE,
  CONSTRAINT `fk_TblOfertaF_U_TblFreelancer1`
    FOREIGN KEY (`idFr`)
    REFERENCES `sistema`.`TblFreelancer` (`idFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TblOfertaF_U_TblAnunUser1`
    FOREIGN KEY (`idAnunUser`)
    REFERENCES `sistema`.`TblAnunUser` (`idAnunUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblProjAnunUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblProjAnunUser` (
  `idProjAnunUser` INT NOT NULL AUTO_INCREMENT,
  `idOfertaFU` INT NOT NULL,
  `DataInicioProjAnunUser` DATE NULL,
  `DataFinalProjAnunUser` DATE NULL,
  PRIMARY KEY (`idProjAnunUser`),
  INDEX `fk_TblProjAnunUser_TblOfertaF_U1_idx` (`idOfertaFU` ASC) VISIBLE,
  CONSTRAINT `fk_TblProjAnunUser_TblOfertaF_U1`
    FOREIGN KEY (`idOfertaFU`)
    REFERENCES `sistema`.`TblOfertaF_U` (`idOfertaFU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblNotiF_U`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblNotiF_U` (
  `idNotiFU` INT NOT NULL AUTO_INCREMENT,
  `idOfertaFU` INT NOT NULL,
  `TipoNotiFU` VARCHAR(45) NULL,
  `MensagemNotiFU` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idNotiFU`),
  INDEX `fk_TblNotiF_U_TblOfertaF_U1_idx` (`idOfertaFU` ASC) VISIBLE,
  CONSTRAINT `fk_TblNotiF_U_TblOfertaF_U1`
    FOREIGN KEY (`idOfertaFU`)
    REFERENCES `sistema`.`TblOfertaF_U` (`idOfertaFU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblComent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblComent` (
  `idComent` INT NOT NULL AUTO_INCREMENT,
  `idFr` INT NOT NULL,
  `idUser` INT NOT NULL,
  `MensagemComent` VARCHAR(255) NULL,
  `NotaComent` DOUBLE NULL,
  PRIMARY KEY (`idComent`),
  INDEX `fk_TblComent_TblFreelancer1_idx` (`idFr` ASC) VISIBLE,
  INDEX `fk_TblComent_TblUsuario1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_TblComent_TblFreelancer1`
    FOREIGN KEY (`idFr`)
    REFERENCES `sistema`.`TblFreelancer` (`idFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TblComent_TblUsuario1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sistema`.`TblUsuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblPort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblPort` (
  `idPort` INT NOT NULL AUTO_INCREMENT,
  `idFr` INT NOT NULL,
  `Imagem1` VARCHAR(100) NULL,
  `Imagem2` VARCHAR(100) NULL,
  `Imagem3` VARCHAR(100) NULL,
  `Desc1` VARCHAR(255) NULL,
  `Desc2` VARCHAR(255) NULL,
  `Desc3` VARCHAR(255) NULL,
  PRIMARY KEY (`idPort`),
  INDEX `fk_TblPort_TblFreelancer1_idx` (`idFr` ASC) VISIBLE,
  CONSTRAINT `fk_TblPort_TblFreelancer1`
    FOREIGN KEY (`idFr`)
    REFERENCES `sistema`.`TblFreelancer` (`idFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sistema`.`TblStatusProjAnunUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblStatusProjAnunUser` (
  `idStatusProjAnunUser` INT NOT NULL AUTO_INCREMENT,
  `idProjAnunUser` INT NOT NULL,
  `StatusProjAnunUser` TINYINT(1) NULL,
  `DiasAtrasadosStatusProjAnunUser` INT NULL,
  PRIMARY KEY (`idStatusProjAnunUser`),
  INDEX `fk_TblStatusProjAnunUser_TblProjAnunUser1_idx` (`idProjAnunUser` ASC) VISIBLE,
  CONSTRAINT `fk_TblStatusProjAnunUser_TblProjAnunUser1`
    FOREIGN KEY (`idProjAnunUser`)
    REFERENCES `sistema`.`TblProjAnunUser` (`idProjAnunUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblAnunFr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblAnunFr` (
  `idAnunFr` INT NOT NULL AUTO_INCREMENT,
  `idFr` INT NOT NULL,
  `NomeServ` VARCHAR(45) NOT NULL,
  `TituloAnunFr` VARCHAR(100) NULL,
  `DescAnunFr` VARCHAR(255) NULL,
  `PrecoAnunFr` DOUBLE NULL,
  `ImgAnunFr` VARCHAR(100) NULL,
  `StatusAnunFr` TINYINT(1) NULL,
  `DataAnunFr` DATE NULL,
  PRIMARY KEY (`idAnunFr`),
  INDEX `fk_TblAnunFr_TblFreelancer1_idx` (`idFr` ASC) VISIBLE,
  INDEX `fk_TblAnunFr_TblTipoServico1_idx` (`NomeServ` ASC) VISIBLE,
  CONSTRAINT `fk_TblAnunFr_TblFreelancer1`
    FOREIGN KEY (`idFr`)
    REFERENCES `sistema`.`TblFreelancer` (`idFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TblAnunFr_TblTipoServico1`
    FOREIGN KEY (`NomeServ`)
    REFERENCES `sistema`.`TblTipoServico` (`NomeServ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblOfertaU_F`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblOfertaU_F` (
  `idOfertaUF` INT NOT NULL AUTO_INCREMENT,
  `idAnunFr` INT NOT NULL,
  `idUser` INT NOT NULL,
  `PropostaOfertaUF` VARCHAR(255) NOT NULL,
  `ImagemOfertaUF` VARCHAR(100) NULL,
  `DataOfertaUF` DATE NOT NULL,
  `StatusOfertaUF` TINYINT(1) NULL,
  `PrecoOfertaUF` DOUBLE NULL,
  PRIMARY KEY (`idOfertaUF`),
  INDEX `fk_TblOfertaU_F_TblAnunFr1_idx` (`idAnunFr` ASC) VISIBLE,
  INDEX `fk_TblOfertaU_F_TblUsuario1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_TblOfertaU_F_TblAnunFr1`
    FOREIGN KEY (`idAnunFr`)
    REFERENCES `sistema`.`TblAnunFr` (`idAnunFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TblOfertaU_F_TblUsuario1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sistema`.`TblUsuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblNotiU_F`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblNotiU_F` (
  `idNotiUF` INT NOT NULL AUTO_INCREMENT,
  `idOfertaUF` INT NOT NULL,
  `TipoNotiUF` VARCHAR(45) NULL,
  `MensagemNotiUF` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idNotiUF`),
  INDEX `fk_TblNotiU_F_TblOfertaU_F1_idx` (`idOfertaUF` ASC) VISIBLE,
  CONSTRAINT `fk_TblNotiU_F_TblOfertaU_F1`
    FOREIGN KEY (`idOfertaUF`)
    REFERENCES `sistema`.`TblOfertaU_F` (`idOfertaUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblProjAnunFr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblProjAnunFr` (
  `idProjAnunFr` INT NOT NULL AUTO_INCREMENT,
  `idOfertaUF` INT NOT NULL,
  `DataInicioProjAnunFr` DATE NULL,
  `DataFinalProjAnunFr` DATE NULL,
  PRIMARY KEY (`idProjAnunFr`),
  INDEX `fk_TblProjAnunFr_TblOfertaU_F1_idx` (`idOfertaUF` ASC) VISIBLE,
  CONSTRAINT `fk_TblProjAnunFr_TblOfertaU_F1`
    FOREIGN KEY (`idOfertaUF`)
    REFERENCES `sistema`.`TblOfertaU_F` (`idOfertaUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblStatusProjAnunFr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblStatusProjAnunFr` (
  `idStatusProjAnunFr` INT NOT NULL AUTO_INCREMENT,
  `idProjAnunFr` INT NOT NULL,
  `StatusProjAnunFr` TINYINT(1) NULL,
  `DiasAtrasadosStatusProjAnunFr` INT NULL,
  PRIMARY KEY (`idStatusProjAnunFr`),
  INDEX `fk_TblStatusProjAnunFr_TblProjAnunFr1_idx` (`idProjAnunFr` ASC) VISIBLE,
  CONSTRAINT `fk_TblStatusProjAnunFr_TblProjAnunFr1`
    FOREIGN KEY (`idProjAnunFr`)
    REFERENCES `sistema`.`TblProjAnunFr` (`idProjAnunFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblPagamentoProjFr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblPagamentoProjFr` (
  `idPagamentoProjFr` INT NOT NULL,
  `idOfertaUF` INT NOT NULL,
  `ValorPagamento` DOUBLE NULL,
  `DataPagamento` DATE NULL,
  PRIMARY KEY (`idPagamentoProjFr`),
  INDEX `fk_TblPagamentoProjFr_TblOfertaU_F1_idx` (`idOfertaUF` ASC) VISIBLE,
  CONSTRAINT `fk_TblPagamentoProjFr_TblOfertaU_F1`
    FOREIGN KEY (`idOfertaUF`)
    REFERENCES `sistema`.`TblOfertaU_F` (`idOfertaUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblPagamentoProjUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblPagamentoProjUser` (
  `idPagamentoProjUser` INT NOT NULL,
  `idOfertaFU` INT NOT NULL,
  `ValorPagamento` DOUBLE NULL,
  `DataPagamento` DATE NULL,
  PRIMARY KEY (`idPagamentoProjUser`),
  INDEX `fk_TblPagamentoProjUser_TblOfertaF_U1_idx` (`idOfertaFU` ASC) VISIBLE,
  CONSTRAINT `fk_TblPagamentoProjUser_TblOfertaF_U1`
    FOREIGN KEY (`idOfertaFU`)
    REFERENCES `sistema`.`TblOfertaF_U` (`idOfertaFU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblChatProjAnunUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblChatProjAnunUser` (
  `idTblChatProj` INT NOT NULL,
  `idProjAnunUser` INT NOT NULL,
  `ChatProjUserMsgTxt` VARCHAR(255) NULL,
  `ChatProjUserMsgDH` DATETIME NULL,
  `ChatProjUserImg` VARCHAR(100) NULL,
  PRIMARY KEY (`idTblChatProj`),
  INDEX `fk_TblChatProjAnunUser_TblProjAnunUser1_idx` (`idProjAnunUser` ASC) VISIBLE,
  CONSTRAINT `fk_TblChatProjAnunUser_TblProjAnunUser1`
    FOREIGN KEY (`idProjAnunUser`)
    REFERENCES `sistema`.`TblProjAnunUser` (`idProjAnunUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`TblChatProjAnunFr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`TblChatProjAnunFr` (
  `idTblChatProj` INT NOT NULL,
  `idProjAnunFr` INT NOT NULL,
  `ChatProjUserMsgTxt` VARCHAR(255) NULL,
  `ChatProjFrMsgDH` DATETIME NULL,
  `ChatProjFrImg` VARCHAR(100) NULL,
  PRIMARY KEY (`idTblChatProj`),
  INDEX `fk_TblChatProjAnunUser_copy1_TblProjAnunFr1_idx` (`idProjAnunFr` ASC) VISIBLE,
  CONSTRAINT `fk_TblChatProjAnunUser_copy1_TblProjAnunFr1`
    FOREIGN KEY (`idProjAnunFr`)
    REFERENCES `sistema`.`TblProjAnunFr` (`idProjAnunFr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO TblTipoServico (NomeServ, CategoriaServ) VALUES
('Design de Logos', 'Design'),
('Design de Interface', 'Design'),
('Web Design', 'Design'),
('Design Thinking', 'Design'),
('Brand Design', 'Design'),
('Design de Produto', 'Design'),
('Design Gráfico', 'Design'),
('Programador Web', 'Programador'),
('Programador Desktop', 'Programador'),
('Programador Mobile', 'Programador'),
('Programador de Jogos', 'Programador'),
('Programador de Sistemas Embarcados', 'Programador'),
('Editor de Vídeos', 'Editor'),
('Editor de Áudio', 'Editor'),
('Editor de Imagens', 'Editor');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;